### ISSUE TITLE
Newline inserted in caption when a reference is embedded

### ISSUE THREAD

**Issue by cgrandin** [pbs-assess/herringsr#1]
When putting a reference to another table in a table caption, the output text appears broken with a newline just before the reference. See 05_tables.Rmd, in the table captions:
e.g.
```cap = "Blah blah blah see Table \\\\@ref(tab:ref-name) blah blah."```

**Comment by seananderson** [comment]
See https://github.com/pbs-assess/csasdown/wiki#faq

**Comment by cgrandin** [comment]
Unfortunately this doesn't work. 

````
```{r storyboard-prd, out.width = "6in", out.height = "6in", fig.cap = "Model output for Pacific Herring in the Prince Rupert District major stock assessment region. See Figure (fig:storyboard-h2g) for description."}
```
````

And this works (puts the reference link in) but adds a newline after the word "Figure"

````
```{r storyboard-prd, out.width = "6in", out.height = "6in", fig.cap = "Model output for Pacific Herring in the Prince Rupert District major stock assessment region. See Figure \\\\@ref(fig:storyboard-hg) for description."}
```
````

I've tried combinations of backslashes but so far using 4 is what builds the link.

**Comment by seananderson** [comment]
Have you tried:

    (ref:my-caption) Model output for Pacific Herring in the Prince Rupert District major stock assessment region. See Figure \@ref(fig:storyboard-hg) for description.
    
    ```{r storyboard-prd, out.width = "6in", out.height = "6in", fig.cap = "(ref:my-caption)"}
    ```

**Comment by cgrandin** [comment]
That does work! If there needed to be R code embedded in there I'm guessing we would just use the triple-tick R syntax inline.

Thanks
