### ISSUE TITLE
add context for GN/ SN quota transferability

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#108]
JC to work with SH on wording (from memo 2020)

**Comment by Shawkshaw** [comment]
This could be described under the MSE section and a mention of how it applies to SOG in the Application of MPs and harvest options for 2022 section.

**Comment by grinnellm** [comment]
Added the table and two placeholders in "03_analysis.Rmd" to discuss the analysis. Still need to fix the table location (floats around).
