### ISSUE TITLE
Updates for 2022 SR

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#113]
Keep track of minor tasks here -- click the three dots and then edit this comment. Create individual issues for larger tasks.
- [x] FSC fishers in CC Area 08 observed only short spot spawns lasting 24 hrs or less. Field observation confirmed egg thickness on kelp and branches was limited to 1 layer for the most part. Herring observed within spawning aggregations were small in size.
- [x]  Change CIs for projection year from vertical line to gray shaded bar (storyboard panel (d); see below).
- [x]  Add retro SBo figure to model diagnostics output

**Comment by grinnellm** [comment]
![plot_d_cc_ppt](https://user-images.githubusercontent.com/25674027/172939153-1a044ac2-b8cd-4ac5-8643-6be477317574.png)

**Comment by grinnellm** [comment]
@jaclyncleary what do you have in mind for the retrospective SB_0 plot? And do you know if anyone else has made one or do I need to start fresh?

**Comment by grinnellm** [comment]
I just noticed that this is already shown in our retrospective SB_t figure (e.g., Figure 31 for HG).

**Comment by jaclyncleary** [comment]
good catch. I'd like to see the points plotted along the x-axis w- associated with each retro year. Then I can update the caption to clarify that these are MPD estimates and also 'long-term average estimates of SBo'  (not dynamic calculation)

**Comment by grinnellm** [comment]
Updated SB_0 to show points along the x-axis (gfiscamutils). I also updated the figure caption.
