### ISSUE TITLE
Autocorrelation plots only show 100 values

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#117]
Our autocorrelation plots only show 100 values but I expect them to have 4,000 points like the MCMC trace plots. 5,000,000 chain length, 1,000th thinning, and 1,000 burn-in makes 4,000 values.

We are on the herring branch of gfiscamutils.

The plot is made [here](https://github.com/pbs-assess/herringsr/blob/121a58f3b7c1a58c6d88efe649150e50e7a49f75/english/20_mcmc_HG.Rmd#L76).

![image](https://user-images.githubusercontent.com/25674027/186025242-63e4fbd4-ba02-4f6e-b396-1db13288b214.png)

**Comment by cgrandin** [comment]
I think you just change the `lag.max` argument.. 

https://github.com/pbs-assess/gfiscamutils/blob/d41552634a5b4c54fe6be2ce371ea1b6968c6ade/R/figures-mcmc-diagnostics.R#L304

**Comment by cgrandin** [comment]
And if you're calling it from `make.autocor.plot()` it's hard coded in there: https://github.com/pbs-assess/gfiscamutils/blob/d41552634a5b4c54fe6be2ce371ea1b6968c6ade/R/figures-mcmc-diagnostics.R#L282

That should be passed in the elippsis ... or as an argument in `make.autocor.plot()`

**Comment by grinnellm** [comment]
Thanks for this @cgrandin.
It could be that I don't understand what the plot is supposed to show.. is it *supposed* to show all 4,000 MCMCs (after thinning and burn-in accounted for)?

**Comment by grinnellm** [comment]
I'm pretty sure I misunderstood what the plot was showing, and it's correct as is.
