### ISSUE TITLE
HCR plots not showing correct data

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#121]
First, this may be moot because these plots seem have a low utility for us. They don't seem to provide much useful information that we use.

However,  I'm not convinced that these figures are correct. For example, Figure 39 and 40 (PRD MPs for DDM and DIM respectively) seem to show the exact same data. In addition, the HR for some panels goes up to 1.0 (see "HS30-60 HR10 cap2.5" in Figure 39). This seems to be just for some MPs with "HR10". 

Figures 39 and 40 are chunks `hcr-prd-1` and `hcr-prd-2` respectively, in "/herringsr/english/21_mcmc_PRD.Rmd."
https://github.com/pbs-assess/herringsr/blob/c79baa20c535f6b6a63b142b1614db3a7d556394/english/21_mcmc_PRD.Rmd#L153
https://github.com/pbs-assess/herringsr/blob/c79baa20c535f6b6a63b142b1614db3a7d556394/english/21_mcmc_PRD.Rmd#L215

**Comment by Sages11** [comment]
The PRD HS30-60HR10Cap2.5 harvest rate goes up to 0.100 on the figure I am looking at. Perhaps you just missed the decimal?

DDM and DIM are the same. Perhaps we only need one?

I believe they might be used especially for those with a cap, to explain how you can have a higher Total-Allowable-Catch with a lower harvest rate when comparing management procedures. This was a question that came up in meetings this week.
