### ISSUE TITLE
Confusion in .csv output headers DONOT UPDATE PLOTS Update storyboard figures d) spawn biomass from B2020 to SB2020 values

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#13]
In herringutils/R/figures.r  Line 700  

Need to replace the reference to B2020:

  proj <- model$mcmccalcs$proj.quants
  proj_yr <- as.numeric(gsub("B", "", colnames(proj)[2]))
  proj_sbt <- as.numeric(c(proj_yr, proj[,2]))
  names(proj_sbt) <- c("year", "lower", "median", "upper")
  proj_sbt <- as_tibble(t(proj_sbt))

**Comment by Shawkshaw** [comment]
Before we do this we should confirm what the iscammcmc_proj_Gear1.csv values are B or SB...

"B0" for the tac==0 column in iscammcmc_proj_Gear1.csv  has the same values as the "sbo" column in the iscam_mcmc.csv file

**Comment by cgrandin** [comment]
They are SBt. See pbs-assess/gfiscam#23
