### ISSUE TITLE
document clarity/ clarity of figures and tables...

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#14]
Sarah- I know you were working on clarity for the storyboard figures/ axes...

**Comment by jaclyncleary** [comment]
Sarah- I know you were working on clarity for the storyboard figures/ axes...

**Comment by grinnellm** [comment]
I agree; it looks like it's been photocopied. I'll look into this.

**Comment by Shawkshaw** [comment]
yes why is the 2018 SR version Chris sent so much clearer?

**Comment by grinnellm** [comment]
I suspect that the 3 of us have an issue with the PDF converter, but Chris does not. Not quite sure what yet, but this reminds me of an issue that I had with LyX once upon a time..

**Comment by grinnellm** [comment]
Once we sort this out, it should be easy to increase the figure resolution (if required). I think it's just the variable `fig_dpi` in "index.Rmd" (line 59). We could increase this to, say, 300, if we want (after we fix the PDF resolution issue).

**Comment by grinnellm** [comment]
Is everyone happy with document clarity including figures and tables?

**Comment by grinnellm** [comment]
Is this resolved for you @jaclyncleary?

**Comment by jaclyncleary** [comment]
yes, thanks!
