### ISSUE TITLE
Confirm iscammcmc_proj_Gear1.csv are SBt projections not Bt for Herring

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#16]
Before we change the tables back and update the HCR reference we need to confirm that the outputs from iscam in the iscammcmc_proj_Gear1.csv file are SBt values and not Bt values as they are currently labeled.

**Comment by Shawkshaw** [comment]
According to notes in the iscam.tpl The main model already does a projection to nyr+1 for sbt which is highly uncertain estimate -- So this is what is found in the iscam_sbt_mcmc.csv column "sbt1_2020"?

iscammcmc_proj_Gear1.csv calculates the SB2020 projection based on an average recruitment rather than highly uncertain estimates?  

.tpl NOTES:
//Overwrite sbt(nyr) so that it does not include estimated Rt(nyr), which is highly uncertain
//This will only be different from sbt(nyr) in the main model if recruits contribute to the spawning population, which is rare

-The values are different for Herring --

**Comment by cgrandin** [comment]
They are SBt. See pbs-assess/gfiscam#23

**Comment by Shawkshaw** [comment]
Thanks Chris! I will close:)

**Comment by cgrandin** [comment]
"According to notes in the iscam.tpl The main model already does a projection to nyr+1 for sbt which is highly uncertain estimate -- So this is what is found in the iscam_sbt_mcmc.csv column "sbt1_2020"?"

Yes!
