### ISSUE TITLE
Confirm hcr is using projected SB2020 from iscammcmc_proj_Gear1.csv

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#17]

**Comment by cgrandin** [comment]
It is not. I will fix the code so they are

**Comment by cgrandin** [comment]
In the case of SOG, the SB2020 from the model is 71.2 but projected is 21.75. Big difference!

**Comment by Shawkshaw** [comment]
hmm I am getting:
SB2020 = 71.2 from iscam_sbt_mcmc.csv  and 
SB2020 = 54.5 from the iscammcmc_proj_Gear1.csv 

still a big difference though

**Comment by cgrandin** [comment]
You are correct, and so is my code. I was looking at another object. The commit I made is good

**Comment by Shawkshaw** [comment]
Thanks Chris!
