### ISSUE TITLE
Automate variables in french figure and table captions

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#19]
Low priority.. after the assessment.

**Comment by cgrandin** [comment]
This should be all done already..

**Comment by grinnellm** [comment]
Mostly, but things like "age-2 to age-10", "90% CI", and "5-year running mean weight-at-age" could be automated -- I already did in the English captions.

**Comment by cgrandin** [comment]
I just realized that and deleted my comment about how it was already done. Oops
