### ISSUE TITLE
Prevent tables for spilling onto next page

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#22]
Not sure if there's an easy fix, but quite a few of the short tables that would easily fit on one page spill over to the next page. Seems like `pandoc` uses `longtable` by default, [which might be the cause](https://stackoverflow.com/questions/27702019/how-to-keep-all-rows-of-a-table-on-the-same-page-in-rmarkdown-when-rendering-a-p)? There are a few suggestions there, but none seem great to me: i.e., we could do this by hand when we're ready to submit by inserting page breaks, but I don't like this manual solution.

**Comment by cgrandin** [comment]
No way to fix this other than put in a \clearpage between the ones you want. That issues a new page

**Comment by cgrandin** [comment]
Also if you change the table font sizes they may fit on one page

**Comment by cgrandin** [comment]
csas_table() has a longtable argument which is TRUE by default. I will make it so the table functions set this to FALSE
