### ISSUE TITLE
Possible issue with the SB2019/SB0 and SB2020/SB0 calculations in Tables 9-13

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#23]
I have confirmed that the values for SB2019, SB2020 and SB0 all match the burned in median values from the .csv files and these seem to be referencing the same places for SB2019/SB0 and SB2020/SB0 but the values are slightly off in the tables... Could be some rounding errors?

![image](https://user-images.githubusercontent.com/6414082/65278700-7c55b800-dae1-11e9-8222-26e5db0d1ba5.png)

**Comment by cgrandin** [comment]
Yes, those tables are rounded to three decimal places. So if your're dividing them, they will be off from the real values
