### ISSUE TITLE
Are storyboard spawn biomass figures (panel d) plotting the SB2020 from the iscam_sbt_mcmc.csv?

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#24]
It looks like the sbt is being plotted with the black line to 2020 and then then projected year from the  iscammcmc_proj_Gear1.csv is actually set on 2021?

ie. here is SoG
![image](https://user-images.githubusercontent.com/6414082/65283596-4b2eb500-daec-11e9-9322-97d8fd8da400.png)

**Comment by jaclyncleary** [comment]
hmm, definitely not what we want.

we need the black line to plot to 2019 (from sbt) and then the point and whiskers for 2020 to come from proj_Gear1.csv

Chris told me he replaced the projection year in sbt_mcmc with the value from proj_Gear1.csv
@cgrandin - can you confirm?

**Comment by cgrandin** [comment]
OK, this should be fixed document-wide. You need to rebuild all the rdata files for it to take effect. There's a toggle in the code for this in index.Rmd, or you can run

```
library(gfiscamutils)
delete.rdata.files("models")
```

**Comment by Shawkshaw** [comment]
I reopened this because the values are corrected but it is still plotting to 2021. 

The final year of the solid black sbt line is the correct value but we want it to be the point and whiskers for 2020 and the solid black line should go to 2019. :)

**Comment by cgrandin** [comment]
OK, I missed that point - I am just finishing up a few more things on this projection replacement code and I will look at that plotting issue
