### ISSUE TITLE
remove red line (3-year trailing moving average smoother) from storyboard fig "e"

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#27]

**Comment by Shawkshaw** [comment]
Done in commit 7b4f0a2.
You need to rebase and rebuild herringutils

**Comment by cgrandin** [comment]
pbs-assess/herringutils@7b4f0a2

**Comment by cgrandin** [comment]
You can use that syntax to create links to commits in other repos

**Comment by grinnellm** [comment]
Thanks Sarah. I removed the sentence in the figure caption that described this line.
