### ISSUE TITLE
Adding retrospective plots to diagnostics?

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#3]
Can we add retrospective plot of spawning biomass to the diagnostic plots? like we had for the 2017 WP?

**Comment by cgrandin** [comment]
We can, but there is currently no retrospective loading code etc. Not hard to do but I don't see any retrospectives in the 2018 models folder. I'm trying to recall exactly how we did it. The code in HerrigAssess loads the retros, so we must have run them previously. I think I did this? Sorry for my bad memory.

**Comment by Shawkshaw** [comment]
Thanks Chris, I will double check with Jaclyn that they are needed with the diagnostic plots.  I did the runs and plotted what I needed to look at in excel for now but if she thinks they should be included I will send you the 2019 retros and we can figure it out from there:)

**Comment by cgrandin** [comment]
I'll need to add the retrospective loading to the new herringutils package anyways for the assessment doc

**Comment by cgrandin** [comment]
I'm halfway done this. I am also adding ability to run retrospectives automatically

**Comment by jaclyncleary** [comment]
thanks on this.
I will need the figure for the presentations, especially for SOG. So having it in the diagnostic plots is  perfect.

**Comment by cgrandin** [comment]
Done. See pbs-assess/gfiscamutils@0232858c88bb99f6151be840edff62725e7959b8, pbs-assess/gfiscamutils@7113b831506df5c749034220fee9bc3d39746219, and 
249f83e60851930549b2dd47962e7749d60956a0
