### ISSUE TITLE
Variable `hcr.wcvi` returns a vector; should return a single number.

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#32]
Search for "TODO" in "03_analysis.Rmd" (around line 311). The R variable `hcr.wcvi` returns a vector of numbers instead of a single value. As it reads, the sentence requires a single value:

Using a HCR with OCPs at $0.5SB_0$ and $0.6SB_0$, a 10\% target harvest rate, and a maximum catch cap of 2,000&nbsp;t, the `r assess_yr + 1` catch calculation is `r f(hcr.wcvi*1000,0)`&nbsp;t.

**Comment by jaclyncleary** [comment]
I'm going to delete these statements and add a range and cite the "new" decision tables. So can be left as is for now.

**Comment by cgrandin** [comment]
Those hcr variables are now vectors of length 2: the hcr TAC and corresponding HR
