### ISSUE TITLE
Add rows to decision tables 19-21 for the DIM and conM stats 

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#35]
Need to add rows for the DIM and conM stats.

The harvest calcs (columns: 2020 TAC and HR) will be the same because these are operating model scenarios, and we use the same assessment model (iscam) in each MP, regardless of OM scenario.

**Comment by cgrandin** [comment]
Warning - this table code is ugly and easy to break!

**Comment by cgrandin** [comment]
If you're adding data, you need to add it to the three csv files in the data folder, i.e. mp-cc.csv, mp-prd.csv, pm-sog.csv

**Comment by Shawkshaw** [comment]
I have added in the new rows and included a new column to specify the OM in the three csv files.  

@cgrandin could you help me with adding the OM to the sorting order?  The tables still have no OM column and are sorting by obj1 when I build the document.
