### ISSUE TITLE
error in PRD text (referencing %Bo)

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#39]
Text says:

The model estimates spawning biomass in 2019, SB 2019 , at 23,223 t (posterior median), equal to
39.7% of SB 0 (Tables 20 & 25). 

However 39.7% isn't correct/ doesn't match Table 25 - not for %Bo in 2019 (==0.389) nor for 2020 (==0.378).

Please check where the number is coming from...

**Comment by Shawkshaw** [comment]
Check closed issue #23  valueshttps://github.com/pbs-assess/herringsr/issues/23

**Comment by jaclyncleary** [comment]
Hmm. This is bound to cause me problems at the meetings.

For the text, can we change these all to whole number, eg 40%? I think this will help.

**Comment by Shawkshaw** [comment]
I could try to change them to the same values if that works better.  Or just type the rounded values in for now?

**Comment by jaclyncleary** [comment]
go with what ever is easiest.

**Comment by Shawkshaw** [comment]
OKay I made the text match the tables manually and we can automate it to do this correctly for next time:) See commit https://github.com/pbs-assess/herringsr/commit/ee98c128d051acaffb7a9694acdbf4cbf1eb3b3c
