### ISSUE TITLE
All diagnostics plots are for WCVI 

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#41]
Sometimes since Sept26th (this was the last time I saved a pdf) the diagnostics plots for all SARs were set to WCVI.  Trying to track down where this happened

**Comment by grinnellm** [comment]
I wonder if this is because I moved the tables from here to the main document, and the variable `model_ind` isn't getting reset and then updated?

**Comment by Shawkshaw** [comment]
I was look at this, can we add that back without adding the tables?  
just adding: model_ind <- match(en2fr("HG", french), major_regions_short) didn't seem to work?

**Comment by cgrandin** [comment]
Yes @grinnellm , that's why. I noticed it at some point and fixed all of them but it's possible they all got deleted again in a merge somewhere. 
This needs to appear in every MCMC Rmd  at the beginning, for each area replaced accordingly. Note Sog is "SoG"
```
model_ind <- match(en2fr("WCVI", french), major_regions_short)
```

**Comment by cgrandin** [comment]
If you want I can do it

**Comment by Shawkshaw** [comment]
I figured it out Chris:)  I will push it with the updates in a few minutes!

**Comment by grinnellm** [comment]
This same issue messed up our recruitment tables -- sorry guys. Again, from when I moved them from the MCMC diagnostic sections to the main doc. All the recruitment tables are for the same SAR.

**Comment by grinnellm** [comment]
I'll try to fix it.

**Comment by grinnellm** [comment]
Done.
