### ISSUE TITLE
adjustment to Tables 29, 30, 31

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#42]
(1) Layout and format is perfect.

(2) I showed the table to FM and we realized that this table needs to clearly communicate that there is no TAC when MPs do not meet the conservation objective.

Thus, please make the following edits:
•	PRD, CC:  For DDM with fixed cutoff – report NA for TAC and HR
•	PRD, CC:  For DIM - report  NA for TAC and HR for all MPs 
•	SOG- no changes

**Comment by cgrandin** [comment]
I’ll work on this this morning when I get in. About 10:30

**Comment by cgrandin** [comment]
By "fixed cutoff" you mean catch cap right?

**Comment by Shawkshaw** [comment]
I think the fixed cutoff would be #1 with the minimum escapement and 20%HR. This one does not meet the conservation objective.

**Comment by jaclyncleary** [comment]
I spoke with chris on the phone and he's clear now. My bad

**Comment by cgrandin** [comment]
Done in pbs-assess/herringutils@65da60525c08156d5f9c69229b86bf055b99e06b
