### ISSUE TITLE
Same TAC and HR for each MP across all 3 OMs

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#43]
I'm not sure if this is an issue, but it's curious that, for example, the TAC and HR for "minE21.2_HR0.1" is the same for DDM, DIM, and conM (5.42, 0.09, respectively; Table 31). Is that correct? This is the same for PRD and CC.

**Comment by jaclyncleary** [comment]
they are coded that way but need to be changed- see issue 42

**Comment by cgrandin** [comment]
Done in pbs-assess/herringutils@65da605
