### ISSUE TITLE
pls fix footnote [^HighProb]  (in 03_analysis.rmd)

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#44]

**Comment by jaclyncleary** [comment]
[^HighProb] is footnote 1 but it's also appearing as footnotes 3, 4, 5.

**Comment by grinnellm** [comment]
It shows up for 3, 4, and 5 because you referred to it again. How about this: Instead of footnotes for 3, 4, and 5, can we just reference DFO (2009)?

**Comment by grinnellm** [comment]
Actually I think there's a way to refer to the same footnote multiple times using LaTeX. Working on it.

**Comment by jaclyncleary** [comment]
we could also just use ^1

**Comment by grinnellm** [comment]
I'd like something robust, so it won't create issues if we add another footnote.

**Comment by cgrandin** [comment]
https://bookdown.org/yihui/bookdown/markdown-syntax.html

**Comment by cgrandin** [comment]
See “Inline formatting” section

**Comment by grinnellm** [comment]
The trick here is referring to the same footnote multiple times, which doesn't seem possible in RMarkdown. I've almost got it working with some LaTeX code.

**Comment by grinnellm** [comment]
This is probably easy @cgrandin, but I can't get the reference in the footnote -- needs to be LaTeX code but seems like it can't find the bib file? See line 277 in 03_"analysis.Rmd" (`\citep{dfo2009}`).

**Comment by cgrandin** [comment]
This is what I see at line 277:
2. Reduction in harvest rate from 20% to 10% was the most effective means of mitigating stock assessment errors by reducing the absolute size of the catch.

Maybe go to the code on GitHub and press the + button and add a comment then it will appear as a new notification and point it out exactly

**Comment by grinnellm** [comment]
Will do. I guess it got moved, now it's 294:)

**Comment by cgrandin** [comment]
OK I found it - good enough

**Comment by grinnellm** [comment]
Thanks -- I haven't figured out how to add a comment on a specific line yet.

**Comment by cgrandin** [comment]
For reference - https://github.com/jgm/pandoc/issues/1603

**Comment by cgrandin** [comment]
I looked at this quite a bit but to no avail. I think you should just leave out the citation

**Comment by grinnellm** [comment]
Thanks Chris.. we tried:)
