### ISSUE TITLE
Add 5th Objective to list of "core fisheries management objectives"

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#49]
This list is at the start of the section "Application of MPs and harvest options for 2020." It is missing a 5th objective that is present in the MP tables:
**minimize P(C_t < 650 t)**
Should we add this one to the list? Or maybe it's not an "official" objective, but more an extension of the other two catch objectives. Let me know and I can add it if needed.

![image](https://user-images.githubusercontent.com/25674027/66338082-4001c480-e8f5-11e9-855f-3a5f8349d3c1.png)

**Comment by jaclyncleary** [comment]
it's not an "official" objective. we use it as a performance metric to show how often the available commercial harvest is below 500t (150t FSC + 500t commercial)
