### ISSUE TITLE
Future update: Add equations for quick reference

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#53]
Add additional pages for the ISCAM, MSE, HCR, etc. equations that can be turned on an off like the diagnostics.  The basis for this can come from the B_equations.rnw in cgrandin/csas-latex but will need to be updated.

**Comment by grinnellm** [comment]
I have added some equations (steady-state model, catch-age model, and a table of symbols and constants). More equations needed I suspect, and this needs some text to help it flow.

**Comment by grinnellm** [comment]
We should also give the equations descriptive labels. For example, change `eq:df14` to `eq:bh-recruitment`. This will make it easier to refer to them in the text, especially if we start adding or removing equations and the numbers aren't consecutive anymore.
