### ISSUE TITLE
Tables of equations (2 and 3)

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#54]
Low priority; after the SR.
Tables are `tab:steady-state-model` and `tab:catch-age-model` in "25_equations.Rmd". They don't fit on one page. These tables need to be either longtables, or maybe just text, not tables.

**Comment by Shawkshaw** [comment]
I think this falls under issue #53 as well

**Comment by grinnellm** [comment]
I agree. I got the tables to fit on one page, but I'm still not convinced the second two tables should be tables -- text makes more sense.
