### ISSUE TITLE
minor stocks - table for spawn index

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#55]
please add a table similar to Table 4  for the minor stock Appendix - with Year and Spawn index for Area 27 and Area 2W, no proportions. This can be 1 table or 2. (you can ask matt if easier)

**Comment by grinnellm** [comment]
I can't figure out why/where the NAs are replaced with zeros. I made a new function `spawn_index_table` in "herringutils."

**Comment by grinnellm** [comment]
The original data.frame has NAs, but it seems like they get replaced with zeros when the kable is written.

**Comment by grinnellm** [comment]
Ah, it's in `add_cols_and_reorder`!
