### ISSUE TITLE
Wrong indentation after 'Sources of information' section

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#56]
The paragraph indentation is wrong in the sections following the section "Sources of information" -- seems like they're indented a similar distance that 'hanging' paragraphs are in the references. This is obvious on Page 43 (start of the Appendix) where the main text is indented and the table caption is not, and on Page 80 (start of the "Model description" section) where it just looks weird.

**Comment by ricardd** [comment]
@grinnellm see my latest pull request on csasdown, perhaps I broke this?

**Comment by grinnellm** [comment]
Hmm, maybe. I did update `csasdown` so that could be it? Though I wouldn't be surprised if it was something else that I did myself:)

**Comment by grinnellm** [comment]
Another image of text after the 'Sources of information'
![image](https://user-images.githubusercontent.com/25674027/67306851-79693100-f4ac-11e9-8422-994e1f47e8e9.png)

**Comment by grinnellm** [comment]
I'm going to close this since I have the temporary cludge which fixes it, and there's [this issue in csasdown](https://github.com/pbs-assess/csasdown/issues/90).
