### ISSUE TITLE
add cross-reference for Reference Points section

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#57]
In this statement (03_Analysis, line 372), can you please add a section cross-reference for Reference Points? (so that one can click on Reference Points) and be taken up to that section. Thanks.

For PRD the best performing MPs generally had 10% or lower harvest rates, although two MPs with a 20% harvest rate did meet the conservation objective because they use a higher lower OCP (see Reference Points) of $0.5\mli{SB}_0$.

**Comment by grinnellm** [comment]
Will do. Is that supposed to say "higher OCP" or "lower OCP"?
