### ISSUE TITLE
NAs in MP table when `french = true`

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#58]
I'm getting NAs in the TAC and HR columns when I generate a French document. I'm not sure, but it might be due to translating the column and row names?
![image](https://user-images.githubusercontent.com/25674027/68249474-c502fb00-ffd3-11e9-8e2b-86713ca4fc75.png)
![image](https://user-images.githubusercontent.com/25674027/68249494-cf24f980-ffd3-11e9-9bed-145222cc8783.png)

**Comment by cgrandin** [comment]
Fixed in pbs-assess/herringutils@5fb09a5255b6d9b059bcec12397a3f8a19747ead and
pbs-assess/gfutilities@58d2c1f6238f5c6ef06e9dfc08a7765e6eafd33c
