### ISSUE TITLE
Better way do differentiate catch in storyboard figres

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#59]
From Jaclyn: A minor suggestion to think on for this year’s stock assessment. I think that even with the 3 colours for catch, it’s too hard to differentiate in a useful way. Do you think it would be better with different colours or hopeless given the long time series?

**Comment by grinnellm** [comment]
Catch since 1972 (i.e., the post-reduction period) is shown in Figure 2. This large figure shows the 3 gear types using **viridis** colours, which have some [good qualities](https://ggplot2.tidyverse.org/reference/scale_viridis.html). I think it works pretty well. I used these same colours in the storyboard figures (panel d) which show catch since 1952. The colours are hard to differentiate because the panel is small. One option is to omit colours from the storyboard catch figure -- the pre-1972 catches are all "other" anyways. Or leave it with colours for those who are able to see them. For example, you can zoom-in on the electronic document to see colours.

**Comment by jaclyncleary** [comment]
thanks for explanation. happy to leave them as is
