### ISSUE TITLE
Can't find hcr.sog and hcr.wcvi

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#6]
These came in with the simulation evaluation for sog and wcvi last year in the "custom-knitr-variables.R" 

I put in the values for now  \Sexpr{f(hcr.sog*1000)}~t = SoG 10,799 t and  \Sexpr{f(hcr.wcvi*1000)}~t = WCVI 0t  but these were generated from the HerringAssess version. 

We will need to add this in for PRD and CC once we have the simulation evaluation in.

**Comment by cgrandin** [comment]
Done in commit 86a7bcb6ff4393ec8a2d6f3b173c04cf6713d545.
You need to rebase and rebuild both `gfiscamutils` and `herringutils` packages
