### ISSUE TITLE
Add section for COVID-19 pandemic

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#64]
Similar to that found in the DataSummaries

**Comment by grinnellm** [comment]
I asked Ann where best to put this section.

**Comment by jaclyncleary** [comment]
> I asked Ann where CSAS would like this section.

did you get a reply, is it okay to leave up front?

**Comment by grinnellm** [comment]
No reply yet but I'll ask again. For now let's leave it there; it's easy to move last minute.

**Comment by grinnellm** [comment]
From Ann:

> Ok, not much more info. from National. For now, could you put it either towards the end of the Context (before the paragraph …This Science Response results from the Science Response of…) or at the beginning of the Analysis and Response? That seems like logical places for it, and hopefully keeps it simple, formatting-wise for now.
