### ISSUE TITLE
fix hardwired percentages in 03_analysis.Rmd

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#68]
found hardwired percentages for SB/SBo

current numbers are correct for 2020 but would prefer if we could change these to be pulled from the table

see lines: 198, 223, 253, 281, 297

thx

**Comment by grinnellm** [comment]
Working on this, but the values aren't quite matching up.

**Comment by grinnellm** [comment]
Done, but see #71.
