### ISSUE TITLE
WCVI Table: Management procedure performance 

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#69]
Please add Management procedure performance table for WCVI - eg, decision_tables_mp(mp.wcvi,...)

rows to include MPs from the excel spreadsheet (some are the same as SOG so you could start by adding what already exists)

leave probabilities blank for now

leave objectives identical to SOG for now (I'm not sure how FM want to handle the new WCVI objectives)

**Comment by grinnellm** [comment]
Do we have the data files for WCVI? Looks like we need "AllMPs_mp-wcvi.csv" and "mp-wcvi.csv." Looks like the second one is a subset of the first one.

**Comment by grinnellm** [comment]
Do we need one for HG as well?
