### ISSUE TITLE
include figure for CC showing spawn by section (in SR in Appendix)

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#70]
JC made a commitment to Heiltsuk to include figure showing spawn/q by section. some modifications needed to figure M2 provided for most recent meeting. Will provide more details shortly

**Comment by grinnellm** [comment]
I can do this, but wondering if that might be better to leave it in the "less formal" data summary report? Also, wondering if it's OK to apply the SAR-level *q* to Sections?

**Comment by grinnellm** [comment]
Do you want all Sections from 1951 to 2020?

**Comment by jaclyncleary** [comment]
Yes all sections. Basically I want the figure you sent me last week for my meeting with the Heiltsuk, which had all of Area 07 and section083(?), just add to it 067

**Comment by jaclyncleary** [comment]
In terms of location- do what's easiest
