### ISSUE TITLE
Calculated depletion values seem to be different than tables

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#71]
Calculated depletion in final year (to insert in the body/text), doesn't quite match values in table. Calculation is in `get_vars()`:
https://github.com/pbs-assess/herringsr/blob/0d7d55d405131a4daeda339356bb7f75f47c53e7/R/variable-setup.R#L205
Gets extracted (for example, PRD) here:
https://github.com/pbs-assess/herringsr/blob/0d7d55d405131a4daeda339356bb7f75f47c53e7/R/variable-setup.R#L231
It's slightly different than the value in the table generated here (**gfiscamutils**):
https://github.com/pbs-assess/herringsr/blob/0d7d55d405131a4daeda339356bb7f75f47c53e7/english/05_tables.Rmd#L484
For example, currently `prd_final_yr_dt` = 46.6%, but the table is 45.2%. The value in the table matches that value in the "Reference points" table (**gfiscamutils**):
https://github.com/pbs-assess/herringsr/blob/0d7d55d405131a4daeda339356bb7f75f47c53e7/english/05_tables.Rmd#L615
Not sure if this is a rounding issue, or due to burn-in, or something else.

**Comment by cgrandin** [comment]
This is where the MCMC depletion is calculated in gfiscamutils: https://github.com/pbs-assess/gfiscamutils/blob/de3c9fb78cdc6fdba52551554bc5b2a1f64e0e3c/R/load-models.R#L216

You should use models[[model_ind]]$mcmccalcs$depl.quants for depletion

**Comment by grinnellm** [comment]
Thanks for that @cgrandin -- I was hoping you'd see this issue:)
Looking at the "Reference points" table, why is it that I can't calculate the same depletion using the values in the table? That is, the table shows SB_0 = 59.182, and SB_2020 = 27.552, so I could calculate depletion is 27.552 / 59.182 = 0.466. But the line for depletion in the table (SB_2020 / SB_0) is 0.452.

**Comment by cgrandin** [comment]
I think SB_0 is actually B_0 and not SSB_0. I know that the depletion value using the code I posted above is right because it is striaght from the MCMC output. We had this same issue last year!

**Comment by grinnellm** [comment]
Shoot. Yes, both @Shawkshaw and I thought it sounded familiar. 
Depletion for 2021 is also weird.

**Comment by grinnellm** [comment]
SB_2021 = 29.698, so calculated depletion is 0.502. Depletion for 2021 in Reference points table is 0.486, but depletion from `major_models[[2]]$mcmccalcs$depl.quants` is 0.453. So three different values.

**Comment by cgrandin** [comment]
What projection model are you using? We did change it. I'm not sure what you're doing this year but if the 2021 value could be coming from the main model run in one set of code and the projection run in the other code.

**Comment by Shawkshaw** [comment]
Yes that is it :( we are using the old projection model from before you made the changes last year - Would I be able to use the up-to-date projection model iscam.exe to rerun the mcevals only for the full model runs done with the old projection model iscam.exe to get the correct .csv model outputs?

**Comment by Shawkshaw** [comment]
Updated projection model version without 2020 biodata: 
![image](https://user-images.githubusercontent.com/6414082/94820525-6a297d80-03b5-11eb-900d-a50e012e253c.png)

**Comment by Shawkshaw** [comment]
@cgrandin after confirming the depletion calculations from the mcmc .csv files we are unsure now that the differences we are seeing in the depletion calculations are from rounding.

I have confirmed that the sbt2020, sbt2021, Sbo values coming out in the herringsr tables match (with some minor rounding differences) the mcmc.csv file outputs.   For example if I do the depletion calculation for PRD sbt2021/Sbo =29.698/59.182 = 0.502 and from iscammcmc_proj_Gear1.csv the median with burning calculation is 29.6947/59.1855 = 0.502 

The table is still showing different depletion values 
![image](https://user-images.githubusercontent.com/6414082/94964361-89f09c80-04ae-11eb-8180-6e7f7835f727.png)

I can not figure out where the `sbt.dat / r.dat$sbo` in the `depl.quants` in gfiscamutils comes from

**Comment by cgrandin** [comment]
Hey @Shawkshaw ,

If you look at the line: https://github.com/pbs-assess/gfiscamutils/blob/de3c9fb78cdc6fdba52551554bc5b2a1f64e0e3c/R/load-models.R#L219

Then do a search backwards for sbt.dat you find: https://github.com/pbs-assess/gfiscamutils/blob/de3c9fb78cdc6fdba52551554bc5b2a1f64e0e3c/R/load-models.R#L203

Then search for where the mc object is made: https://github.com/pbs-assess/gfiscamutils/blob/de3c9fb78cdc6fdba52551554bc5b2a1f64e0e3c/R/load-models.R#L128

In the line above that, the mcmc is read in from the files via `read.mcmc()`

If you look at that function you'll see that they come straight from the MCMC csv files in the MCMC output folder.
If you're in RStudio use Ctrl-Shift-F to search for things through the whole project. Maybe you already knew about it but it helps a lot.

**Comment by Shawkshaw** [comment]
Thanks Chris - I am still struggling to understand why if I am getting a SBt2021/SBo depletion value of 0.502 using the median values from the .csv files calculation, does the depl.quants calculation give us 0.486 for the 50% column in the table?   -->I realize this is a vary minor difference but it is driving us nuts 👎

**Comment by cgrandin** [comment]
I will take a look - I haven't been building this year's doc so I'll try to track it through last year's model output. I have to step out for the afternoon but will take a look later on.

**Comment by Shawkshaw** [comment]
I think I figured it out -- The depl.quants calculation is doing the sbt2021/SBo calculation at every mcsave (so it generates 4000 with the burnin) and then it takes the median of these depletion values.  If I do this calculation manually from the .csv file I get 0.486 which matches the value in the table.

**Comment by cgrandin** [comment]
Ok I found the reason there are two end-year depletion values. The value is calculated here: https://github.com/pbs-assess/gfiscamutils/blob/de3c9fb78cdc6fdba52551554bc5b2a1f64e0e3c/R/load-models.R#L219 and this is simply the value taken from the model without any projection applied. The second value, and the one which appears in the table, is calculated after the `sbt.dat` dataframe's final year column has been modified inside this `if()` code: https://github.com/pbs-assess/gfiscamutils/blob/de3c9fb78cdc6fdba52551554bc5b2a1f64e0e3c/R/load-models.R#L326 on this line: https://github.com/pbs-assess/gfiscamutils/blob/de3c9fb78cdc6fdba52551554bc5b2a1f64e0e3c/R/load-models.R#L342

It depends what you want to do. If you're happy with using the projected value then leave it as-is. If not, the table should use `depl.quants[,ncol(depl.quants)]`. If that's the case, just modify `r.quants` here: https://github.com/pbs-assess/gfiscamutils/blob/de3c9fb78cdc6fdba52551554bc5b2a1f64e0e3c/R/load-models.R#L379.

Note you have to delete the `aaa_gfiscam.RData` files in the model's directories to run this code.

**Comment by Shawkshaw** [comment]
Thanks Chris - I think I have a good idea of which values are being calculated and used in the tables/text now.  

One question we still have that perhaps you have some insight:  Is it standard to calculate the depletion using mcmc estimates as dt=median(SBt)/median(SBo) or dt=median(SBt/SBo) ? The later is the way you have it coded - is this the way it is calculated in Hake? Hopefully that makes sense

**Comment by cgrandin** [comment]
You have it right, depletion should be calculated for each posterior sample and then the median of those taken
