### ISSUE TITLE
Add WCVI biomass objectives to the MP table

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#72]
WCVI has 3 additional biomass objectives. Something like this - @grinnellm is this easy or a formatting nightmare?  Tackle this after text is edited
![image](https://user-images.githubusercontent.com/6414082/94879128-3893cf00-0414-11eb-9878-849e22da2a7e.png)

**Comment by grinnellm** [comment]
I'll look at this now. Can you confirm that we need 7 columns under the Biomass header?

**Comment by Shawkshaw** [comment]
No only 4 - This is how the table looks now:
![image](https://user-images.githubusercontent.com/6414082/94941977-864b1e80-048a-11eb-9d9f-6170665c0eb5.png)

We would like to add the 3 additional ones like in the table above: P(Bt>.65B0), P(Bt>.75B0) & P(Bt>Bave)

**Comment by grinnellm** [comment]
Looking briefly at how this is made (`decision_tables_mp()` in **herringutils**) it seems like this might be tricky and may require a new function. Can you please confirm the best approach @cgrandin?

**Comment by jaclyncleary** [comment]
can you make this as a new table (so that we have two options for tables for WCVI), i.e.,  so that we have quick access to both formats as needed.

**Comment by cgrandin** [comment]
It's much easier to copy/paste that whole function and make a new one. You would add the new objectives headers amongst the ones there: https://github.com/pbs-assess/herringutils/blob/0a8cd483f932d4ab44865855f2d65f2d3806bae8/R/tables.R#L307

This (https://github.com/pbs-assess/herringutils/blob/0a8cd483f932d4ab44865855f2d65f2d3806bae8/R/tables.R#L292) would have to change to `cline("1-12")` and assuming they are Biomass objectives and not Conservation objectives, you will need to add ampersands here (https://github.com/pbs-assess/herringutils/blob/0a8cd483f932d4ab44865855f2d65f2d3806bae8/R/tables.R#L296) like in the Yield header.

These are always a huge pain, so what I do is knit it into latex, copy the latex code for the table only and build the latex by itself. It is like 100x faster that way. I spent a bunch of time making a test platform which I've attached. Paste the table code into a.tex (overwrite the table code there
[test-latex-tables.zip](https://github.com/pbs-assess/herringsr/files/5319608/test-latex-tables.zip)
) and run build.bat to produce a.pdf, which will have your table.

**Comment by cgrandin** [comment]
This also needs to change: https://github.com/pbs-assess/herringutils/blob/0a8cd483f932d4ab44865855f2d65f2d3806bae8/R/tables.R#L259

**Comment by grinnellm** [comment]
Thanks for all the @cgrandin  -- I can tell this is going to be a struggle, I mean, challenge:)

**Comment by grinnellm** [comment]
@Shawkshaw can you add the mp table for WCVI with extra columns to `/data/`.

**Comment by grinnellm** [comment]
Table has been added but I''m keeping this open until the formatting is done (horizontal and vertical lines in the table header).
![image](https://user-images.githubusercontent.com/25674027/95361965-42895800-0882-11eb-8fe0-74d8bedfbe08.png)
