### ISSUE TITLE
small edit to MP options for PRD and CC tables

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#73]
Remove "historical MPs" from PRD and CC tables (already removed from SOG and WCVI)

*Needed for today*

PRD- remove minE12.1_HR0.2
CC- remove minE17.6_HR0.2

(only appears in DDM scenario)

thanks.

**Comment by Shawkshaw** [comment]
Done in 
https://github.com/pbs-assess/herringsr/commit/8b35ffdad46b2e4559c38a1b000bf80400c3b7ff
