### ISSUE TITLE
Double check SoG age-2's

### ISSUE THREAD

**Issue by grinnellm** [pbs-assess/herringsr#8]
From @jaclyncleary:
Can you please take a look at the proportions age for SOG? I see from the data summary that prop_age2 in 2019 is 0.238, which is largest in the last 10 years and a 55% increase over the next highest (0.153 in 2016).

In the model we see a massive recruitment of age-2s and I just want your help to make sure the input data are sound (you know, triple check) before we start writing the narrative.

**Comment by grinnellm** [comment]
I'm going to go through the data in R first, then go back to the database. In R, I see 11,811 fish that were sampled in 2019. Of these, 9,574 fish are from seine gear (gear code 29); these are from 117 samples. This agrees with the data summary so far. There are 2,275 age-2 fish: 2,275 / 9,574 = 0.238 so that is making sense.

**Comment by grinnellm** [comment]
If I look at the proportion age-2 per sample (i.e., for each of the 117 samples), I get the following histogram. The vertical line is 0.238.
![image](https://user-images.githubusercontent.com/25674027/65004622-e8ea7000-d8b1-11e9-85f5-193446fed725.png)

**Comment by grinnellm** [comment]
Next, I'll look if 0.238 is unusually high. I plotted a histogram of the proportion age-2 since 1951. Again, the vertical line is 0.238. 2019 is high, but it seems to range from 0 to 0.3. Again, doesn't look like anything is awry to me.
![image](https://user-images.githubusercontent.com/25674027/65005020-5054ef80-d8b3-11e9-96b5-f6cd3cf01f0e.png)

**Comment by grinnellm** [comment]
This all comes from the data that I read into R, some of which is in the data summaries. Kristen looked over the data summaries and I don't think anything seemed incorrect to her. If you want, I can dig further (in R, or in the MS Access databases). Digging into the MS Access data isn't straight forward but I can do it -- it'll just take some time.

**Comment by grinnellm** [comment]
One more plot:) Here's the time series of proportion age-2; horizontal line is 0.238.
![image](https://user-images.githubusercontent.com/25674027/65005565-1c7ac980-d8b5-11e9-8363-c43da5076c25.png)

**Comment by jaclyncleary** [comment]
Matt, this is all really great and I don't think we need to go back into the database. From the last plot, looks like 2006 is the last year with similarly high prop age-2s, but in looking at the storyboard plot, it doesn't correspond to high numbers of age-2, nor high index. Nor high index in the subsequent year (2007).

**Comment by grinnellm** [comment]
I've done some more on this -- see my recent commits. The data and R code is in `herringsr/PropAge`. If you source the `Bio.R` script you'll see some figures in that folder. There's also a summary of the data, "Summary.csv".

**Comment by jaclyncleary** [comment]
these figures are great
