### ISSUE TITLE
spawn proportion tables (Tables 4: 8)

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#82]
Table 4- change column 3 header to 006
Table 5- change column 3 headers to 03, 04, 05
Table 6- ... to 06, 07, 08

proportion calculations: for each of Tables 5, 7 and 8, the same proportions appear for 2020 and 2021. This is not the case however for Tables 4 and 6. Please check the calculations.

**Comment by Shawkshaw** [comment]
The SI proportions need to be updated for all the stocks in the .csv files in the \data folders 
Also see issue [#78](https://github.com/pbs-assess/herringsr/issues/78)

**Comment by grinnellm** [comment]
For Table 4 (HG) column names, do you want
006, 021&025, and 023&024
or
Cumshewa/Selwyn, Juan Perez/Skincuttle, and Louscoone?

**Comment by jaclyncleary** [comment]
slight preference for the names but do what is easiest
