### ISSUE TITLE
Include a section describing the potential impacts of aquaculture herring incidental catch

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#88]
Waiting on more detailed data from the aquaculture group to include a general summary of the potential impacts in each SAR.

**Comment by grinnellm** [comment]
Options for display:

1. Table showing which PFMAs correspond to which Statistical Areas and SARs.
1. Figure with one panel for each SAR, with bar plots of number released and dead by year (i.e., similar to Figure 2, total landed catch).

May want to tweak years to align with herring seasons.

**Comment by grinnellm** [comment]
I'm working on bringing this data into the document via the DataSummaries repo.
