### ISSUE TITLE
retrospective plot (model diagnostics) - also links to issue #2 in gfiscamutils

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#89]
@grinnellm 

- [x]  Please shorten time series to 1988-present (full dive time series)

- [x]  Also, is it possible for you to add the index values/ scaled abundance from storyboard plot (a) to this plot? Using triangle symbol please to aid with comparisons between these figures.

- [x]  retro plots don't seem to match the storyboard figures. Possibly off by one year. Pls check, I'd like to have these on hand for the fall meetings (even tho not currently in SR).

**Comment by grinnellm** [comment]
https://github.com/pbs-assess/herringsr/commit/5ace67699b99905f1b519dbbe2462434140f67a4

**Comment by grinnellm** [comment]
https://github.com/pbs-assess/gfiscamutils/commit/85908d691cd781af7ce0d944df39dfd8a0a5124c
