### ISSUE TITLE
help with tables showing management procedure options for SoG, PRD, and CC

### ISSUE THREAD

**Issue by jaclyncleary** [pbs-assess/herringsr#9]
Chris- these are the tables I need to add to the Herring SR, they would appear as Tables 14,16, replacing the probabilistic decision tables.

[MP Tables for the SR_16Sep19.docx](https://github.com/pbs-assess/herringsr/files/3619284/MP.Tables.for.the.SR_16Sep19.docx)

**Comment by cgrandin** [comment]
What does "These rows are populated by the MPs in column 3" mean?

**Comment by jaclyncleary** [comment]
so in the current SR we have this statement for SoG "The 2020 recommended catch calculated by applying the MP is 10,799"

Instead I want to include a table that applies the MP (column 3) and outputs the recomended catch. For SoG we can currently just inlcude the 1 MP (HS30_60_0.2HR_cap30.0) but for PRD and CC, management are requesting all options for consultation.

**Comment by jaclyncleary** [comment]
I can ask Sam too for the MP code if that helps

**Comment by cgrandin** [comment]
I already have his code. I'm thinking this table can be automated then

**Comment by cgrandin** [comment]
I think I need to know how the values in this table are calculated. I'm not sure what I'm looking at. To get a probability, is these some counts of computed values from posteriors? Can you tell me why the topmost left number is 79%, if so I may be able to figure out the rest

**Comment by cgrandin** [comment]
Maybe I don't have his code for this after all...

**Comment by cgrandin** [comment]
I added them in 5eb7290ae3976c1bfd200b297cbacab6ef191fd6 but I don't know how to populate the last column so we will have to sit down and talk about this @jaclyncleary 

You need to rebase and rebuild csasdown to get the tabularx environment for latex which is necessary for these tables to render

**Comment by cgrandin** [comment]
Done in commit 45fcffea8028e2b04ebf70d88fddbdadff1a2b80 and pbs-assess/herringutils@f6652f2520138c2775188fbfeaffce6150ef42d3
