### ISSUE TITLE
PDR MP Table too long for page

### ISSUE THREAD

**Issue by Shawkshaw** [pbs-assess/herringsr#93]
Table 29 too long for page

**Comment by grinnellm** [comment]
Related issue https://github.com/pbs-assess/csasdown/issues/156

**Comment by grinnellm** [comment]
Fixed the "double header and footer rules" issue in the above commit, but I think it's missing the header text "Pacifc Region   Science Response...". And the table is too long. It's too bad PDR is the first table (has the full caption) and has so many lines in the table -- this would not be an issue if CC was first and had the caption.

**Comment by grinnellm** [comment]
Header is now there, thanks to @maburton.
https://github.com/pbs-assess/csasdown/pull/194#issuecomment-900478768
Waiting to see if any rows can be omitted. If not, we will look into options. Either wrap the table onto two pages, or shrink the font.
