### ISSUE TITLE
Missing area definitions in Central Coast spawn index legend

### ISSUE THREAD

**Issue by Sages11** [pbs-assess/herringsr#96]
(Labeled as figure 10 currently)

Current:
Legend: 067 is Kitasu Bay, 074 is Thompson/Stryker, 072 is Lower Spiller, and 078 is Upper Spiller.

Need: 073, 075, 076, 077, 086

**Comment by grinnellm** [comment]
I think that was all they wanted. Do they/JC want more now?

**Comment by Sages11** [comment]
There are currently 9 in the plot. So either we need to remove the other 5 from the plot, or add to the legend.

**Comment by jaclyncleary** [comment]
I have clarified the figure caption to state that the 4 names are the "key spawning areas".
Context:  DFO refer to them by section number but local managers and FNs refer to them by common name (so this helps us know which section we're all talking about)
